int_arr=input().split(" ")
print(int(int_arr[0])+int(int_arr[1]))
print(int(int_arr[0])-int(int_arr[1]))
print(int(int_arr[0])*int(int_arr[1]))
print(int(int(int_arr[0])/int(int_arr[1])))
print(int(int_arr[0])%int(int_arr[1]))
